CREATE DATABASE IF NOT EXISTS todo_list

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT NOT NULL AUTO_INCREMENT,
    description VARCHAR(255) NOT NULL,
    status TINYINT NOT NULL,
    PRIMARY KEY (id)
);